### ISSUE TITLE
no ipaddress displayed on terminal

### ISSUE THREAD

**Issue by drepou** [JavierIH/miniKame#1]
Hi JavierIH

I try your sample code on my nodeMCU amica V2 i noticed that ipAddress of the board is not correctly written by  "Serial.println(WiFi.localIP());" in main.cpp

checked on arduino sample code this look to work much better :

```
    IPAddress myIP = WiFi.softAPIP();
    Serial.print("AP IP address: ");
Serial.println(myIP);
```

![2016-07-16 13_49_14-main cpp d__bricolage et electronique_electronique_robots_minikame-develop_min](https://cloud.githubusercontent.com/assets/15879331/16894632/2fca295c-4b5c-11e6-9583-92272b70755c.png)

Best Regards Yohan

**Comment by JavierIH** [comment]
Hi drepou

You are right, I have just checked the code and it wasn't working properly. I'm going to update it with your code, which seems to work fine.

Thank you very much for your feedback!!!!!

**Comment by drepou** [comment]
My plaisure to share and contribute...
Still Wait for my bearing to mount my kame

See you
Yohan

Envoyé de mon iPhone
