### ISSUE TITLE
BodyB.stl file is wrong

### ISSUE THREAD

**Issue by ThorsAvenger** [JavierIH/miniKame#3]
The stl file for the part bodyB is wrong. Perhaps it got mixed up with another model?
https://github.com/JavierIH/miniKame/blob/develop/parts/stl/bodyB.stl

**Comment by JavierIH** [comment]
Hi @ThorsAvenger , you are right this file is part of another robot, I have no idea what it is doing here...
Thank you very much for your feedback!
